<a href="https://colab.research.google.com/github/joyjixu/qm2_resources/blob/main/data_preprocessing/merge_tweets_days.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Since the tweet csvs we hydrated are hour-by-hour, we need to merge them to get one csv per day in April

First you'll need to upload all 24 csvs for one day onto Colab, and replace the value of the 'day' variable below with the actual day

In [ ]:
day = '01' #format: dd

In [ ]:
import pandas as pd

In [ ]:
# we initialize the day dataframe to be the one for hour 00, then we will concatenate all the other hours to it
df_day = pd.read_csv('coronavirus_tweets_us_04_{day}_00.csv'.format(day=day), engine='python')

for i in range(1,24):
  if i < 10:
    hour = '0{}'.format(i)
  else:
    hour = '{}'.format(i)

  path = '/content/coronavirus_tweets_us_04_{day}_{hour}.csv'.format(day=day, hour=hour)
  print(path)
  
  df_hour = pd.read_csv(path, engine='python')

  df_day = pd.concat([df_day,df_hour], ignore_index = True)

/content/coronavirus_tweets_us_04_01_06.csv
/content/coronavirus_tweets_us_04_01_07.csv
/content/coronavirus_tweets_us_04_01_08.csv
/content/coronavirus_tweets_us_04_01_09.csv
/content/coronavirus_tweets_us_04_01_10.csv
/content/coronavirus_tweets_us_04_01_11.csv
/content/coronavirus_tweets_us_04_01_12.csv
/content/coronavirus_tweets_us_04_01_13.csv
/content/coronavirus_tweets_us_04_01_14.csv
/content/coronavirus_tweets_us_04_01_15.csv
/content/coronavirus_tweets_us_04_01_16.csv
/content/coronavirus_tweets_us_04_01_17.csv
/content/coronavirus_tweets_us_04_01_18.csv
/content/coronavirus_tweets_us_04_01_19.csv
/content/coronavirus_tweets_us_04_01_20.csv
/content/coronavirus_tweets_us_04_01_21.csv
/content/coronavirus_tweets_us_04_01_22.csv
/content/coronavirus_tweets_us_04_01_23.csv

In [ ]:
df_day.info

<bound method DataFrame.info of       coordinates                      created_at  ... is_state state
0             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    WA
1             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    NY
2             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    KY
3             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    OR
4             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    WA
...           ...                             ...  ...      ...   ...
63238         NaN  Wed Apr 01 23:45:47 +0000 2020  ...     True    CT
63239         NaN  Wed Apr 01 23:45:47 +0000 2020  ...     True    MN
63240         NaN  Wed Apr 01 23:45:46 +0000 2020  ...     True    NJ
63241         NaN  Wed Apr 01 23:45:47 +0000 2020  ...     True    MA
63242         NaN  Wed Apr 01 23:45:47 +0000 2020  ...     True    VA

[63243 rows x 36 columns]>

In [ ]:
df_day

      coordinates                      created_at  ... is_state state
0             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    WA
1             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    NY
2             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    KY
3             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    OR
4             NaN  Wed Apr 01 00:05:04 +0000 2020  ...     True    WA
...           ...                             ...  ...      ...   ...
63238         NaN  Wed Apr 01 23:45:47 +0000 2020  ...     True    CT
63239         NaN  Wed Apr 01 23:45:47 +0000 2020  ...     True    MN
63240         NaN  Wed Apr 01 23:45:46 +0000 2020  ...     True    NJ
63241         NaN  Wed Apr 01 23:45:47 +0000 2020  ...     True    MA
63242         NaN  Wed Apr 01 23:45:47 +0000 2020  ...     True    VA

[63243 rows x 36 columns]

Finally we can save the day as a csv again (you don't need to change the file name here)

In [ ]:
df_day.to_csv('daily_coronavirus_tweets_us_04_{day}.csv'.format(day=day))

Make sure to download!